
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-courses-f24-02
owner: ucsb-cs156-f24
repo_name: proj-courses-f24-02
pull_requests: [{"author":{"id":"U_kgDOB2W7yQ","is_bot":false,"login":"berdly","name":"Jakob Pinedo"},"headRefName":"berdly-SingleButtonJobForm","number":28,"title":"Added SingleButtonJobForm component","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-02/pull/28"},{"author":{"id":"U_kgDOB3Cn0w","is_bot":false,"login":"EduinoMEH","name":"Edwin E. Medrano Villela"},"headRefName":"proj-eduinomeh-issue-10","number":27,"title":"Created Placeholder Page for Updates, Accessible Only by Admin(s)","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-02/pull/27"},{"author":{"id":"U_kgDOBt27wQ","is_bot":false,"login":"vedp3705","name":""},"headRefName":"JobControllerFix-Issue-8","number":22,"title":"Get job by ID added to controller file","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-02/pull/22"},{"author":{"id":"U_kgDOBuPHZA","is_bot":false,"login":"leozhu0","name":""},"headRefName":"leozhu0-proj-issue-1","number":18,"title":"Added Helpful Error Message When User Adds Two Sections of the Same Course to Schedule","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-02/pull/18"},{"author":{"id":"U_kgDOB2W7yQ","is_bot":false,"login":"berdly","name":"Jakob Pinedo"},"headRefName":"berdly-proj-issue-5","number":17,"title":"Added getActiveQuarters method to UCSBAPIQuarterService and /api/public/activeQuarters endpoint","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-02/pull/17"},{"author":{"id":"MDQ6VXNlcjI5Njc5MDYz","is_bot":false,"login":"billybobjoe123","name":""},"headRefName":"billybobjoe123-proj-issue-11","number":15,"title":"made descriptions optional ","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-02/pull/15"}]
