
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-courses-f24-02
owner: ucsb-cs156-f24
repo_name: proj-courses-f24-02
pull_requests: [{"author":{"id":"MDQ6VXNlcjY1ODc1MjE3","is_bot":false,"login":"rushil-x-gupta","name":""},"headRefName":"rg-logclutter","number":30,"title":"Reduced clutter in log from course update jobs","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-02/pull/30"},{"author":{"id":"U_kgDOBt27wQ","is_bot":false,"login":"vedp3705","name":""},"headRefName":"JobControllerFix-Issue-8","number":22,"title":"Get job by ID added to controller file","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-02/pull/22"}]
